name: Stellpire
description: An absolute bare-bones web app.
# version: 1.0.0
# homepage:
# author: Martin Lyrå <martin.lyra.97@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  yaml: ^2.1.15

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
