name: Stellpire
description: An absolute bare-bones web app.
# version: 1.0.0
# homepage:
# author: Martin Lyrå <martin.lyra.97@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  angular_components: ^0.9.0
  pdx_data_tools:
    git: git://github.com/martinlyra/pdx_data_tools.git

dev_dependencies:
  angular_test: ^2.0.0
  build_runner: ^0.10.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.0.0

# Non-angular dev
#dev_dependencies:
#  build_runner: ^0.10.0
#  build_web_compilers: ^0.4.0
